=== marianod323/ClassServicesBot/languages/lang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by Mariano Dorneles (Universidade Federal de Santa Maria) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="language">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="command">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="type" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="error">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="type" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="ref" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== marianod323/ClassServicesBot/languages/lang_eng.xml
<?xml version="1.0" encoding="UTF-8"?>
<language ref="english" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lang.xsd">
	<command name="userla">
		<item type="title">Users last activity</item>
		<item type="help">Shows the users last activity on server</item>
		<item type="date">%m/%d/%Y, %H:%M</item>
		<item type="field1_name">User</item>
		<item type="field1_content">last activity on</item>
		<item type="field2_name">Page</item>
		<item type="field2_content">has no recent activity on text channel</item>
		<item type="field3_name">Help</item>
		<item type="field3_content">To navigate through pages, use **cs-userla _PAGE\_NUMBER_**</item>
	</command>
	<error name="userla_error">
		<item type="title">Oops...</item>
		<item type="field1_name">Error</item>
		<item type="field1_content">I've found an error on handling your request, maybe you forgot to specify the page number?</item>
		<item type="field2">Help</item>
		<item type="field2_content">To navigate through pages, use **cs-userla _PAGE\_NUMBER_**</item>
	</error>
</language>

=== marianod323/ClassServicesBot/languages/lang_ptbr.xml
<?xml version="1.0" encoding="UTF-8"?>
<language ref="português_brasileiro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lang.xsd">
	<command name="userla">
		<item type="title">Última atividade dos usuários</item>
		<item type="help">Mostra a última atividade dos usuários no servidor</item>
		<item type="date">%d/%m/%Y, %H:%M</item>
		<item type="field1_name">Usuário</item>
		<item type="field1_content">última atividade em</item>
		<item type="field2_name">Página</item>
		<item type="field2_content">não possui atividade recente no canal</item>
		<item type="field3_name">Ajuda</item>
		<item type="field3_content">Para navegar entre as páginas, use **cs-userla _NÚMERO\_DA\_PÁGINA_**</item>
	</command>
	<error name="userla_error">
		<item type="title">Oops...</item>
		<item type="field1_name">Erro</item>
		<item type="field1_content">Encontrei um erro ao processar seu pedido, por acaso você esqueceu de colocar o número da página?</item>
		<item type="field2">Ajuda</item>
		<item type="field2_content">Para navegar entre as páginas, use **cs-userla _NÚMERO\_DA\_PÁGINA_**</item>
	</error>
	<command name="usercount">
		<item type="title">Quantidade de usuários</item>
		<item type="help">Mostra a quantidade de usuários e bots no servidor</item>
		<item type="field1_name">Usuários</item>
		<item type="field2_name">Bots</item>
	</command>
	<command name="help">
		<item type="title">Ajuda</item>
		<item type="help">Ensina como utilizar cada comando</item>
		<item type="prefix">cs-</item>
		<item type="field1_name">Como usar os comandos</item>
		<item type="field1_content">Para chamar os comandos do bot, digite o comando no em um canal de texto</item>
		<item type="field2_name">userla _NÚMERO\_DA\_PÁGINA_</item>
		<item type="field3_name">usercount</item>
		<item type="field4_name">help</item>
	</command>
</language>
